apiVersion: v1
kind: pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: 637423270289.dkr.ecr.ap-south-1.amazonaws.com/node:1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
